# -*- coding: utf-8 -*-
"""03_ReggressionN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yxeBeSgv1Puqsfou6HOyiepAWqZEvgcO

**3η Εργασία - Regression**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_diabetes
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import KFold, RandomizedSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, max_error

from sklearn.ensemble import RandomForestRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.svm import SVR
from sklearn.linear_model import ElasticNet

import shap
import os

# Fix seed for reproducibility
SEED = 42
np.random.seed(SEED)

diabetes_data = load_diabetes(as_frame=True, scaled=False)

X = diabetes_data.data
y = diabetes_data.target.rename("target")

print("Number of samples:", X.shape[0])    # 442
print("Number of features:", X.shape[1])   # 10
print("Feature names:", diabetes_data.feature_names)

"""2. PRINT RANGE OF ONE COLUMN"""

print("Range of BMI feature:")
print("Min:", X["bmi"].min())
print("Max:", X["bmi"].max())

"""3. CHECK & REMOVE NaNs"""

print("NaNs in features:\n", X.isna().sum())
print("NaNs in target:", y.isna().sum())

# Remove rows with NaNs (if any)
data = pd.concat([X, y], axis=1).dropna().reset_index(drop=True)

X = data[diabetes_data.feature_names]
y = data["target"]

feature_names = diabetes_data.feature_names

"""4. HISTOGRAM OF TARGET"""

plt.figure()
plt.hist(y, bins=30)
plt.xlabel("Target value")
plt.ylabel("Frequency")
plt.title("Histogram of Diabetes Target")
plt.show()

"""5. MIN–MAX SCALING (INPUT & OUTPUT)"""

# NOTE: Global scaling is shown for demonstration,
# but for KFold we fit scalers per-fold to avoid leakage.

"""6-7. K-FOLD SETUP (6 FOLDS)"""

kf = KFold(n_splits=6, shuffle=True, random_state=SEED)

"""8. CSV DATA STRUCTURE"""

# Create a list to store the data
csv_data = []
# Append header row
csv_data.append([
    "Model", "Set", "Fold",
    "Max_n", "RMSE_n", "MAE_n", "MAPE_n",
    "Max", "RMSE", "MAE", "MAPE"
])

"""9. MODELS & HYPERPARAMETERS"""

# Metric function MAPE to avoid division by zero
def mape(y_true, y_pred, eps=1e-9):
    y_true = np.asarray(y_true).reshape(-1)
    y_pred = np.asarray(y_pred).reshape(-1)
    denom = np.maximum(np.abs(y_true), eps)
    return 100.0 * np.mean(np.abs((y_true - y_pred) / denom))

models = {
    "RandomForest": (
        RandomForestRegressor(random_state=SEED),
        {
            "n_estimators": [100, 200, 300],
            "max_depth": [None, 5, 10],
            "min_samples_split": [2, 5]
        }
    ),
    "GaussianProcess": (
        GaussianProcessRegressor(),
        {
            "alpha": [1e-10, 1e-5, 1e-2]
        }
    ),
    "SVR": (
        SVR(),
        {
            "C": [0.1, 1, 10],
            "gamma": ["scale", "auto"]
        }
    ),
    "ElasticNet": (
        ElasticNet(random_state=SEED),
        {
            "alpha": [0.01, 0.1, 1.0],
            "l1_ratio": [0.2, 0.5, 0.8]
        }
    )
}

# Folder for saving SHAP plots
SHAP_DIR = "shap_outputs"
os.makedirs(SHAP_DIR, exist_ok=True)

"""9. MAIN K-FOLD LOOP"""

#Start the KFold loop
for fold_id, (train_idx, test_idx) in enumerate(kf.split(X), start=1):

    # 9.a Training the model according to train data
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    # Fold-wise Min-Max scaling (fit on train, transform test) to avoid leakage
    scaler_X = MinMaxScaler()
    scaler_y = MinMaxScaler()

    X_train = scaler_X.fit_transform(X_train)
    X_test  = scaler_X.transform(X_test)

    y_train = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
    y_test  = scaler_y.transform(y_test.values.reshape(-1, 1)).ravel()

    X_train = pd.DataFrame(X_train, columns=feature_names)
    X_test  = pd.DataFrame(X_test,  columns=feature_names)

    for model_name, (model, param_grid) in models.items():

        # 9.b Calculating the best parameters
        search = RandomizedSearchCV(
            estimator=model,
            param_distributions=param_grid,
            n_iter=5,
            cv=3,
            random_state=SEED,
            n_jobs=-1
        )

        search.fit(X_train, y_train)
        best_model = search.best_estimator_

        # 9.c Predictions (normalized)
        y_train_pred_n = best_model.predict(X_train)
        y_test_pred_n = best_model.predict(X_test)

        # 9.d Denormalize the values
        y_train_true = scaler_y.inverse_transform(y_train.reshape(-1, 1)).ravel()
        y_test_true = scaler_y.inverse_transform(y_test.reshape(-1, 1)).ravel()

        y_train_pred = scaler_y.inverse_transform(y_train_pred_n.reshape(-1, 1)).ravel()
        y_test_pred = scaler_y.inverse_transform(y_test_pred_n.reshape(-1, 1)).ravel()


        # 9.e Error metrics calculation

        metrics_test = [
            max_error(y_test_true, y_test_pred),
            np.sqrt(mean_squared_error(y_test_true, y_test_pred)),
            mean_absolute_error(y_test_true, y_test_pred),
            mape(y_test_true, y_test_pred)
        ]

        metrics_test_n = [
            max_error(y_test, y_test_pred_n),
            np.sqrt(mean_squared_error(y_test, y_test_pred_n)),
            mean_absolute_error(y_test, y_test_pred_n),
            mape(y_test, y_test_pred_n)
        ]

        metrics_train = [
            max_error(y_train_true, y_train_pred),
            np.sqrt(mean_squared_error(y_train_true, y_train_pred)),
            mean_absolute_error(y_train_true, y_train_pred),
            mape(y_train_true, y_train_pred)
        ]

        metrics_train_n = [
            max_error(y_train, y_train_pred_n),
            np.sqrt(mean_squared_error(y_train, y_train_pred_n)),
            mean_absolute_error(y_train, y_train_pred_n),
            mape(y_train, y_train_pred_n)
        ]

        # 9.f Actual vs Predicted plot
        plt.figure()
        plt.scatter(y_test_true, y_test_pred)
        plt.plot([y_test_true.min(), y_test_true.max()],
                 [y_test_true.min(), y_test_true.max()], 'r--')
        plt.xlabel("Actual")
        plt.ylabel("Predicted")
        plt.title(f"{model_name} – Fold {fold_id}")
        plt.show()

        # 9.g Append to csv
        csv_data.append([model_name, "Train", fold_id, *metrics_train_n, *metrics_train])
        csv_data.append([model_name, "Test",  fold_id, *metrics_test_n,  *metrics_test])

        # 9.h SHAP explainer
        X_train_df = pd.DataFrame(X_train, columns=feature_names)
        X_test_df  = pd.DataFrame(X_test,  columns=feature_names)

        background = shap.sample(X_train_df, min(100, len(X_train_df)), random_state=SEED)

        X_test_shap = X_test_df.iloc[:30].copy()

        try:
            masker = shap.maskers.Independent(background)
            explainer = shap.Explainer(best_model.predict, masker)
            shap_values = explainer(X_test_shap)

            shap.summary_plot(shap_values, X_test_shap, show=False)
            plt.title(f"SHAP Summary – {model_name} – Fold {fold_id}")
            plt.tight_layout()
            plt.savefig(os.path.join(SHAP_DIR, f"{model_name}_fold{fold_id}_summary.png"), dpi=200)
            plt.show()

            shap.plots.waterfall(shap_values[0], show=False)
            plt.title(f"SHAP Waterfall #1 – {model_name} – Fold {fold_id}")
            plt.tight_layout()
            plt.savefig(os.path.join(SHAP_DIR, f"{model_name}_fold{fold_id}_waterfall1.png"), dpi=200)
            plt.show()

            if len(X_test_shap) > 1:
                shap.plots.waterfall(shap_values[1], show=False)
                plt.title(f"SHAP Waterfall #2 – {model_name} – Fold {fold_id}")
                plt.tight_layout()
                plt.savefig(os.path.join(SHAP_DIR, f"{model_name}_fold{fold_id}_waterfall2.png"), dpi=200)
                plt.show()

        except Exception as e:
            print(f"[SHAP warning] {model_name} fold {fold_id}: {e}")

results_df = pd.DataFrame(csv_data[1:], columns=csv_data[0])
results_df.to_csv("results.csv", index=False)
results_df.head(10)

summary_test = (
    results_df[results_df["Set"] == "Test"]
    .groupby("Model")[["RMSE", "MAE", "MAPE", "Max"]]
    .agg(["mean", "std"])
)
summary_test